version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Denver
      - PLEX_CLAIM=claim-xuT7ATxQVrkqbCnp3n97
      - ADVERTISE_IP=http://192.168.7.124:32400/
      - PLEX_UID=1000
      - PLEX_GID=1000
    hostname: tinyplex 
    volumes:
      - /data/appdata/plex/config:/config
      - /data/appdata/plex/tmp:/transcode
      - /data/tv:/data/tv
      - /data/movies:/data/movies
